# Generated by Django 4.1.2 on 2023-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mxikobject_mxik_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxikobject',
            name='mxik_deleted_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
